fridge-rescue/fridge-rescue-server

src/main/java/team/rescue/fridge/recipe/entity/Recipe.java, src/main/java/team/rescue/fridge/recipe/entity/RecipeDto.java, src/main/java/team/rescue/fridge/recipe/entity/RecipeIngredient.java, src/main/java/team/rescue/fridge/recipe/entity/RecipeIngredientDto.java, src/main/java/team/rescue/fridge/recipe/entity/RecipeStep.java, src/main/java/team/rescue/fridge/recipe/entity/RecipeStepDto.java
엔티티 생성
recipe
recipe_step
recipe_ingredient
<pre><code>
CREATE TABLE recipe (
recipe_id  bigint NOT NULL,
member_id bigint NOT NULL,
title  VARCHAR(100) NOT NULL,
summary  VARCHAR(100),
review_count int NOT NULL,
created_at timestamp  NOT NULL,
MODIFIED_AT timestamp,
recipe_image_url varchar(100),
PRIMARY KEY(recipe_id),
foreign key (member_id) references member(member_id)
)
CREATE TABLE recipe_ingredient (
recipe_ingredient_id  bigint NOT NULL,
recipe_id bigint NOT NULL,
name    VARCHAR(20),
amount    VARCHAR(20),
PRIMARY KEY(recipe_ingredient_id),
foreign key (recipe_id) references recipe(recipe_id)
)
CREATE TABLE recipe_step (
recipe_step_id  bigint NOT NULL,
recipe_id bigint NOT NULL,
step_no int NOT NULL,
step_contents    VARCHAR(100),
step_tip    VARCHAR(100),
PRIMARY …
=>  Recipe 테이블 생성 및 Entity 매핑 #4

sql/ddl.sql, src/main/java/team/rescue/recipe/entity/Bookmark.java, src/main/java/team/rescue/recipe/entity/Recipe.java
북마크 테이블 생성 및 엔티티 매핑
**AS-IS**
**TO-BE**
- 멤버(1):북마크(N), 북마크(N):레시피(1) 관계 매핑
=> 북마크 테이블 생성 및 엔티티 매핑 #48

sql/ddl.sql, src/main/java/team/rescue/recipe/entity/Recipe.java
레시피 테이블에 조회수 컬럼 추가
**AS-IS**
**TO-BE**
- ERD Cloud 업데이트 완료
- ddl.yml 파일 업데이트 완료
- Entity 필드 추가
=> 레시피 테이블에 조회수 컬럼 추가 #49

src/main/java/team/rescue/auth/controller/AuthController.java, src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java, src/main/java/team/rescue/auth/service/AuthService.java, src/main/java/team/rescue/common/dto/ResponseDto.java, src/main/java/team/rescue/error/GlobalExceptionHandler.java, src/main/java/team/rescue/error/exception/AuthException.java, src/main/java/team/rescue/error/exception/UserException.java, src/main/java/team/rescue/error/exception/ValidationException.java, src/main/java/team/rescue/error/type/AuthError.java, src/main/java/team/rescue/error/type/UserError.java
- RestControllerAdvice로 서블릿 단의 예외를 핸들링하도록 처리
- 커스텀 예외 클래스 작성 및 각 예외 Enum으로 정의
- 공통 응답 DTO 작성(모든 응답 데이터 Wrapping)
**AS-IS**
1. 응답 시 DTO 반환
2. 각 서비스 메서드에서 `throw new RuntimeException`으로 임시 처리
**TO-BE**
1. ResponseDto<T>를 통해 응답 DTO를 한 번 감싸서 응답
에러 코드에 대해서는 프론트와 이야기를 해보면 좋을 것 같습니다.
지금은 대부분의 경우 HTTP Method로 구분이 가능한 것 같아서 불필요하다는 생각인데,
우선 -1을 기본값으로 해두었습니다.
```java
@Getter
public class ResponseDto<T> {
private int code = -1;    // 프론트와 이후 정의할 에러 코드(HTTP Method로 구분 불가한 경우를 구분하기 위함)
private String message = null;    // 응답 메세지
private final T data;    // 응답 DTO
@Builder
public ResponseDto(int code, String message, T data) {
this.code = code;
this.message = message;
this.data = data;
}
}
```
2. 서블릿 단 예외는 GlobalExceptionHandler(ControllerAdvice)에서 핸들링
- ControllerAdvice에서 로그를 찍도록 변경
- 예외 발생 지점에서는 아래와 …
=> 프로젝트 공통 예외 처리 및 공통 응답값 DTO 정의 #23

src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java, src/main/java/team/rescue/auth/handler/OAuthAuthorizationSuccessHandler.java, src/main/java/team/rescue/config/SecurityConfig.java, src/main/java/team/rescue/member/entity/Member.java
**AS-IS**
로그인 수행 이후 refresh token 테이블에 저장하는 부분 누락
**TO-BE**
로그인 이후 refresh token 테이블에 저장하도록 수정
=> 로그인 이후 refresh token 테이블에 저장 #63

src/main/java/team/rescue/auth/controller/AuthController.java, src/main/java/team/rescue/auth/service/AuthService.java, src/main/java/team/rescue/fridge/repository/FridgeRepository.java, src/test/java/team/rescue/auth/controller/AuthControllerTest.java, src/test/java/team/rescue/auth/service/AuthServiceTest.java
**AS-IS**
**TO-BE**
회원 탈퇴 기능 구현하였습니다.
회원을 탈퇴할 때 냉장고를 가진 회원은 탈퇴가 되지 않아 냉장고를 먼저 삭제하는 로직을 추가했습니다.
=> 회원 탈퇴 기능 구현 #37

src/main/java/team/rescue/fridge/controller/FridgeController.java, src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java, src/main/java/team/rescue/fridge/service/FridgeService.java, src/test/java/team/rescue/fridge/controller/FridgeControllerTest.java, src/test/java/team/rescue/fridge/service/FridgeServiceTest.java
**AS-IS**
기존의 API 테스트를 통해서 냉장고 관련 기능을 테스트
**TO-BE**
테스트 코드를 작성해서 검증
=> FridgeController, FridgeService 테스트 코드 작성 #67

src/main/java/team/rescue/auth/controller/AuthController.java, src/main/java/team/rescue/auth/service/AuthService.java, src/test/java/team/rescue/auth/controller/AuthControllerTest.java, src/test/java/team/rescue/auth/service/AuthServiceTest.java
**AS-IS**
**TO-BE**
로그아웃 시 redis와 db에 있는 RefreshToken 값을 null로 변경하는 기능을 구현했습니다.
=> 로그아웃 기능 구현 #97

src/main/java/team/rescue/error/type/ServiceError.java, src/main/java/team/rescue/notification/controller/NotificationController.java, src/main/java/team/rescue/notification/dto/NotificationDto.java, src/main/java/team/rescue/notification/entity/Notification.java, src/main/java/team/rescue/notification/repository/NotificationRepository.java, src/main/java/team/rescue/notification/service/NotificationService.java, src/test/java/team/rescue/notification/controller/NotificationControllerTest.java, src/test/java/team/rescue/notification/service/NotificationServiceTest.java
**AS-IS**
**TO-BE**
모든 알림 내역 조회,
특정 알림 내역 조회,
알림 일괄 확인 처리 기능 구현했습니다.
=> 알림 확인 기능 구현 #40

src/main/java/team/rescue/auth/dto/JoinDto.java, src/main/java/team/rescue/member/dto/MemberDto.java
**AS-IS**
기존 영문 한글 숫자 제한이 있어서 연동시 조금씩 혼란이 있었습니다.
**TO-BE**
영문 한글 숫자 제한을 일단 제거하고, 값 필수여부와 글자 수만 남겼습니다.
=> refact: Validation 부분 값 필수 부분과 글자 수만 남겨놓고 나머지 제거

src/main/java/team/rescue/cook/dto/CookDto.java, src/main/java/team/rescue/cook/repository/CookRepository.java, src/main/java/team/rescue/member/controller/MemberController.java, src/main/java/team/rescue/member/dto/MemberDto.java, src/main/java/team/rescue/member/service/MemberService.java, src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/review/dto/ReviewDto.java, src/main/java/team/rescue/review/repository/ReviewRepository.java, src/test/java/team/rescue/member/controller/MemberControllerTest.java, src/test/java/team/rescue/member/service/MemberServiceTest.java
**AS-IS**
**TO-BE**
회원이 완료한 요리를 조회할 수 있는 기능을 구현했습니다.
레시피에 대한 리뷰까지는 굳이 필요할 것 같지 않아서 리뷰 부분 응답은 제외했습니다.(API 명세도 수정)
=> 완료된 요리 조회 기능 구현 #38

src/main/java/team/rescue/member/controller/MemberController.java, src/main/java/team/rescue/member/service/MemberService.java, src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/repository/BookmarkRepository.java, src/main/java/team/rescue/recipe/repository/RecipeRepository.java, src/test/java/team/rescue/member/controller/MemberControllerTest.java, src/test/java/team/rescue/member/service/MemberServiceTest.java, src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
**AS-IS**
**TO-BE**
사용자가 등록한 레시피 내역을 조회하는 기능, 사용자가 북마크한 레시피를 조회하는 기능을 구현했습니다.
=> 등록한 레시피, 북마크한 레시피 내역 조회 #114

src/main/java/team/rescue/error/type/ServiceError.java, src/main/java/team/rescue/recipe/entity/Recipe.java, src/main/java/team/rescue/review/controller/ReviewController.java, src/main/java/team/rescue/review/dto/ReviewDto.java, src/main/java/team/rescue/review/entity/Review.java, src/main/java/team/rescue/review/service/ReviewService.java
- 리뷰 수정
- 리뷰 삭제
**AS-IS**
**TO-BE**
```java
public void decreaseReviewCount() {
this.reviewCount--;
}
```
하단 코드 권한 오류로 수정해두었는데 괜찮을지 확인 부탁드립니다
```java
// 기존
RECIPE_MEMBER_UNMATCHED(HttpStatus.BAD_REQUEST, "레시피를 작성한 회원이 아닙니다."),
// 수정
RECIPE_MEMBER_UNMATCHED(HttpStatus.UNAUTHORIZED, "레시피를 작성한 회원이 아닙니다."),
```
=> 리뷰 수정, 삭제 기능 구현 #31

src/main/java/team/rescue/recipe/controller/RecipeController.java, src/main/java/team/rescue/recipe/service/RecipeService.java, src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java
**AS-IS**
**TO-BE**
컨플릭 해결시 놓친 코드 수정하였습니다
=> 컨플릭 해결시 놓친 코드 수정

src/main/java/team/rescue/recipe/entity/Recipe.java, src/main/java/team/rescue/report/controller/ReportController.java, src/main/java/team/rescue/report/dto/ReportDto.java, src/main/java/team/rescue/report/repository/ReportRepository.java, src/main/java/team/rescue/report/service/ReportService.java
- 레시피 신고 기능
```java
@Getter
@Setter
public static class ReportCreateDto {
@NotEmpty(message = "신고 대상 레시피 아이디는 필수값입니다.")
private Long recipeId;
@NotEmpty(message = "신고 이유를 입력해주세요.")
@Size(max = 200, message = "200자 미만으로 입력해주세요.")
private String reason;
}
```
- 신고 시 레시피 신고 카운트 증가 처리
- prefix: report_recipe
=> 신고 기능 구현 #25

src/main/java/team/rescue/auth/controller/AuthController.java
=> 인증 요청값 파라미터 이름 변경 providerType -> provider

src/main/java/team/rescue/error/GlobalExceptionHandler.java, src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/dto/RecipeStepDto.java, src/main/java/team/rescue/recipe/entity/RecipeStep.java, src/main/java/team/rescue/recipe/service/RecipeService.java, src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java, src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
**AS-IS**
명세서에 맞춰서 레시피 스탭의 필드를 수정하였습니다.
**TO-BE**
=> 명세서에 맞춰서 레시피 필드 수정

src/main/java/team/rescue/search/controller/SearchController.java
**AS-IS**
@PathVariable 로 되어있던걸 @RequestParam으로 수정하였습니다.
**TO-BE**
=> 명세에 따라 @RequestParam으로 변경

src/main/java/team/rescue/fridge/controller/FridgeController.java, src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java, src/main/java/team/rescue/fridge/service/FridgeService.java
**AS-IS**
재료 수정 dto deleteItem, updateItem 네이밍 사용
**TO-BE**
delete와 update로 네이밍 수정 및 PutMapping -> PatchMapping으로 변경
=> 냉장고 재료 일괄 수정 및 삭제 DTO 변경 #161

src/main/java/team/rescue/fridge/dto/FridgeIngredientDto.java
**AS-IS**
유통기한이 오늘까지인 재료 등록이 불가능
**TO-BE**
유통기한이 오늘까지인 재료도 등록 가능하도록 수정
=> 유통기한 유효성 검증 수정 #166

src/main/java/team/rescue/aop/RequestValidAop.java, src/main/java/team/rescue/config/ElasticsearchConfig.java, src/main/java/team/rescue/recipe/controller/RecipeController.java, src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/dto/RecipeIngredientDto.java, src/main/java/team/rescue/recipe/dto/RecipeStepDto.java, src/main/java/team/rescue/recipe/service/RecipeService.java, src/main/java/team/rescue/search/controller/SearchController.java, src/main/java/team/rescue/search/dto/RecipeSearchDto.java, src/main/java/team/rescue/search/entity/RecipeDoc.java, src/main/java/team/rescue/search/repository/RecipeSearchRepository.java, src/main/java/team/rescue/search/service/RecipeSearchService.java, src/main/java/team/rescue/search/type/SortType.java, src/test/java/team/rescue/recipe/controller/RecipeControllerTest.java, src/test/java/team/rescue/recipe/service/RecipeServiceTest.java
- 검색 기능 관련 컨트롤러, 서비스 메서드 추가
- 레시피 등록, 수정 DTO 변경점 반영
Mulfipart/form-data, application/json 타입(request)을 분리해 파라미터를 받도록 변경했습니다.
검색 기능 관련 컨트롤러를 추가해 두었습니다.
- 자동완성
- 키워드 기반 검색
- 냉장고 재료 기반 검색
레시피 등록 시 레시피 도큐먼트를 생성해 저장하는 부분을 구현해 두었습니다.

=> 검색 기능 관련 컨트롤러, 리포지토리 일부 구현 및 레시피 DTO 변경점 반영

src/main/java/team/rescue/auth/controller/AuthController.java
**AS-IS**
이메일 인증이 권한 상관없이 가능하도록 되어 있음
**TO-BE**
이메일 인증 GUEST 권한만 가능하도록 수정
=> emailConfirm 메소드 인가처리 수정 #168

src/main/java/team/rescue/auth/controller/AuthController.java, src/main/java/team/rescue/auth/dto/JoinDto.java
**AS-IS**
**TO-BE**
회원가입 상황에서도 이메일 인증이 가능하도록 변경
=> 이메일 인증 로직 변경 #174

src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
dto에 맞춰서 레시피 업데이트 부분을 수정하였습니다.
**TO-BE**
빠른 작업을 위해, 기존의 레시피를 삭제해버리고, 새로 업데이트 할 레시피를 등록시키는 방식으로 하였습니다.
추후에 개별 업데이트하는 코드로 수정할 예정입니다.
RecipeUpdateDto 에서 기존 필드 이름인 recipeIngredients, recipeSteps를 RecipeCreateDto 필드에 맞춰 수정하였습니다.
=> 레시피 업데이트 수정

src/main/java/team/rescue/auth/controller/AuthController.java, src/main/java/team/rescue/auth/service/AuthService.java, src/main/java/team/rescue/member/dto/MemberDto.java
**AS-IS**
이메일 인증 이후 role만 변경
**TO-BE**
role을 변경하면 토큰 정보도 바뀌기 때문에 바뀐 토큰 정보를 내려줘야 함
=> 이메일 인증 이후 access token 재발급 #179

src/main/java/team/rescue/review/entity/Review.java, src/main/java/team/rescue/review/service/ReviewService.java
**AS-IS**
리뷰 수정부분 요청에 이미지 파일이 없을 시에 이미지가 삭제 및 업로드 되는 부분을 수정하였습니다.
**TO-BE**
=> 리뷰 수정 이미지부분 코드 수정

src/main/java/team/rescue/recipe/entity/Recipe.java, src/main/java/team/rescue/recipe/service/RecipeService.java, src/main/java/team/rescue/review/service/ReviewService.java
**AS-IS**
**TO-BE**
레시피 조회 시 카운트 증가, 리뷰 카운트 증가 기능 추가하였습니다
=> 레시피 조회 카운트, 리뷰 카운트 증가 기능 추가

src/main/java/team/rescue/recipe/controller/RecipeController.java, src/main/java/team/rescue/recipe/repository/RecipeRepository.java, src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
**TO-BE**
최신 레시피, 인기 레시피 목록을 가져오는 기능을 구현했습니다.
인기 레시피는 북마크 수가 많은 경우 인기있는 레시피로 생각합니다.
=> 최신 레시피, 인기 레시피 목록

src/main/java/team/rescue/search/controller/SearchController.java, src/main/java/team/rescue/search/repository/RecipeSearchRepository.java, src/main/java/team/rescue/search/service/RecipeSearchService.java
**AS-IS**
**TO-BE**
Elasticsearch를 이용해 사용자의 냉장고 속 재료를 기반으로 레시피를 검색해서
냉장고 재료가 가장 많이 포함된 레시피를 우선적으로 보여주는 기능을 구현했습니다.
=> 냉장고 재료 기반 레시피 검색 기능 구현 #34

src/main/java/team/rescue/member/controller/MemberController.java, src/main/java/team/rescue/member/service/MemberService.java, src/main/java/team/rescue/recipe/controller/RecipeController.java, src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/repository/BookmarkRepository.java, src/main/java/team/rescue/recipe/service/RecipeService.java
- 기타 레시피 목록 조회는 info 데이터 반환하도록 변경
- 북마크 레시피 목록 조회
- 최신, 리뷰순 레시피 목록 조회
=> 레시피 상세 조회 시 북마크 여부 포함하도록 변경 #191

src/main/java/team/rescue/error/type/ServiceError.java, src/main/java/team/rescue/report/repository/ReportRepository.java, src/main/java/team/rescue/report/service/ReportService.java
- 이미 신고한 레시피를 다시 신고하는 경우 409 에러 반환
=> 이미 신고한 레시피를 다시 신고하는 경우 409 에러 반환 #195

src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
최신 레시피 목록, 인기 레시피 목록을 가져올 때 lazy 로딩으로 인한 에러 발생
**TO-BE**
트랜잭션을 설정하여 lazy 로딩 에러가 발생하지 않도록 수정
=> 최신 레시피, 인기 레시피 프록시 에러 수정 #203

src/main/java/team/rescue/error/type/ServiceError.java, src/main/java/team/rescue/search/repository/RecipeSearchRepository.java, src/main/java/team/rescue/search/service/RecipeSearchService.java
**AS-IS**
키워드 기반 검색기능 공백 포함해서 검색하면 생기던 오류를 수정하였습니다.
**TO-BE**
=> 키워드 기반 검색기능 공백포함하도록 수정

src/main/java/team/rescue/recipe/dto/RecipeDto.java, src/main/java/team/rescue/recipe/dto/RecipeStepDto.java, src/main/java/team/rescue/recipe/entity/RecipeStep.java, src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
레시피 스탭 이미지 처리를 위해 수정하였습니다.
테스트케이스로는
1. 기존 스탭 이미지와 내용을 수정
2. 기존 스탭 이미지와 내용이 있고 + 새로운 스탭만 추가 / 이미지와 함께 추가
3. 기존 스탭 이미지와 내용을 부분 제거, 새로운 스탭만 추가 / 이미지와 함께 추가
**TO-BE**
기존 스탭 이미지의 타입 검증과 관련해서는 추후 프론트와 함께 테스트 해보며 맞춰나갈 예정입니다.
=> 레시피 수정 스탭 이미지 처리 구현

src/main/java/team/rescue/auth/filter/JwtAuthenticationFilter.java, src/main/java/team/rescue/config/RedisConfig.java, src/main/java/team/rescue/config/SecurityConfig.java, src/main/java/team/rescue/notification/RedisSubscriber.java, src/main/java/team/rescue/notification/controller/NotificationController.java, src/main/java/team/rescue/notification/dto/NotificationDto.java, src/main/java/team/rescue/notification/entity/Notification.java, src/main/java/team/rescue/notification/event/NotificationEvent.java, src/main/java/team/rescue/notification/event/NotificationEventHandler.java, src/main/java/team/rescue/notification/event/NotificationEventPublisher.java, src/main/java/team/rescue/notification/repository/NotificationRepository.java, src/main/java/team/rescue/notification/repository/SseEmitterRepository.java, src/main/java/team/rescue/notification/service/NotificationService.java, src/main/java/team/rescue/notification/service/RedisMessageService.java, src/main/java/team/rescue/notification/service/SseEmitterService.java, src/main/java/team/rescue/search/entity/RecipeDoc.java
**AS-IS**
**TO-BE**
redis pub/sub과 SSE를 이용해 로그인 시에 냉장고의 재료 중 유통기한이 하루 남은 재료가 있다면 알림을 생성하도록 했습니다.
=> 유효기간 1일 남은 재료 로그인 시 알림 #41

src/main/java/team/rescue/common/schedule/report/ReportScheduler.java, src/main/java/team/rescue/recipe/entity/Recipe.java, src/main/java/team/rescue/recipe/service/RecipeService.java
- 0시에 신고 개수가 10개 초과한 레시피 일괄 블라인드(block) 처리 
- 
- 스케줄링 적용
=> 0시에 신고 개수 10개 이상인 레시피 블라인드 처리 #58

src/main/java/team/rescue/search/entity/RecipeDoc.java, src/main/java/team/rescue/search/repository/RecipeSearchRepository.java, src/main/java/team/rescue/search/service/RecipeSearchService.java
**AS-IS**
키워드에 공백 유무에 따라 검색이 가능하도록 수정하였습니다.
ex) "당근 오이", "김밥김밥"
**TO-BE**
=> 키워드 기반 검색기능 키워드에 공백 유무에 따라 검색하도록 수정

src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
레시피 수정시 대표이미지가 변경이 없어서 string이 올때, 타입체크하는 부분을 추가해주었습니다.
**TO-BE**
=> 레시피 수정시 이미지 변경이 없으면, 기존 이미지 유지하도록 수정

src/main/java/team/rescue/recipe/controller/RecipeController.java, src/main/java/team/rescue/recipe/entity/Recipe.java, src/main/java/team/rescue/recipe/service/RecipeService.java
**AS-IS**
레시피 수정시 recipeImage 유무 확인부분 수정하고 레시피 삭제 권한 수정하였습니다
**TO-BE**
=> 레시피 수정시 recipeImage 유무 확인부분 수정, 레시피 삭제 권한 수정

src/main/java/team/rescue/review/service/ReviewService.java
**AS-IS**
**TO-BE**
레시피에 리뷰를 작성했을 때 작성자에게 알림이 가도록 구현했습니다.
=> 리뷰 작성시 알림 발행 #42

src/main/java/team/rescue/recipe/controller/RecipeController.java
**AS-IS**
recipeImage required false 처리 하였습니다.
**TO-BE**
=> 레시피 수정시 recipeImage required false 처리

src/main/java/team/rescue/recipe/service/RecipeService.java
=> 레시피 수정시 recipeImage null 체크
